name: Deploy Nodejs code on EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # in github runner: got access to your code
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # inside github runner: pull, build and push docker image
      - name: Build and push
        run: |
          docker build -t itsm16/new-triage:latest .
          docker push itsm16/new-triage:latest
      
      # github runner machine ssh to ec2
      - name: SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          # got into ec2
          script: |
            cat > .env <<EOF
            BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
            BETTER_AUTH_GOOGLE_CLIENT_ID=${{ secrets.BETTER_AUTH_GOOGLE_CLIENT_ID }}
            BETTER_AUTH_GOOGLE_CLIENT_SECRET=${{ secrets.BETTER_AUTH_GOOGLE_CLIENT_SECRET }}
            BETTER_AUTH_URL=${{ vars.BETTER_AUTH_URL }}
            APP_URL=${{ vars.APP_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            CORSAIR_KEK=${{ secrets.CORSAIR_KEK }}
            TOPIC=${{ secrets.TOPIC }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            EOF
            
            cat > /home/ubuntu/Caddyfile <<EOF
            :80 {
                reverse_proxy triage:3000
            }
            EOF

            sudo docker network create triage-network || true
            sudo docker stop triage || true
            sudo docker rm triage || true
            sudo docker stop caddy || true
            sudo docker rm caddy || true
            sudo docker image prune -af
            sudo docker pull itsm16/new-triage:latest
            sudo docker pull caddy:latest
            sudo docker run -d \
              --name triage \
              --network triage-network \
              --restart unless-stopped \
              --env-file .env \
              itsm16/new-triage:latest

            sudo docker run -d \
              --name caddy \
              --network triage-network \
              --restart unless-stopped \
              -p 80:80 \
              -p 443:443 \
              -v /home/ubuntu/Caddyfile:/etc/caddy/Caddyfile \
              -v caddy_data:/data \
              -v caddy_config:/config \
              caddy:latest
            sudo docker container prune -f
            rm -f .env